/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevelopmentRouteImport } from './routes/_authenticated/development'
import { Route as AuthenticatedGamificationRouteImport } from './routes/_authenticated/gamification'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTestsRouteImport } from './routes/_authenticated/tests'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicConsentRouteImport } from './routes/_public/consent'
import { Route as PublicContactsRouteImport } from './routes/_public/contacts'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicManagementRouteImport } from './routes/_public/management'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated/admin/assignments'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminDevelopmentRouteImport } from './routes/_authenticated/admin/development'
import { Route as AuthenticatedAdminDictionariesRouteImport } from './routes/_authenticated/admin/dictionaries'
import { Route as AuthenticatedAdminExportRouteImport } from './routes/_authenticated/admin/export'
import { Route as AuthenticatedAdminGamificationRouteImport } from './routes/_authenticated/admin/gamification'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminMaterialsRouteImport } from './routes/_authenticated/admin/materials'
import { Route as AuthenticatedAdminOrgRouteImport } from './routes/_authenticated/admin/org'
import { Route as AuthenticatedAdminProductionRouteImport } from './routes/_authenticated/admin/production'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTestsRouteImport } from './routes/_authenticated/admin/tests'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedLearningIndexRouteImport } from './routes/_authenticated/learning.index'
import { Route as AuthenticatedLearningCourseIdRouteImport } from './routes/_authenticated/learning.$courseId'
import { Route as AuthenticatedProfessionsIndexRouteImport } from './routes/_authenticated/professions.index'
import { Route as AuthenticatedProfessionsSlugRouteImport } from './routes/_authenticated/professions.$slug'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results.index'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedTestProfessionIdRouteImport } from './routes/_authenticated/test.$professionId'
import { Route as PublicTrainingIndexRouteImport } from './routes/_public/training.index'
import { Route as PublicTrainingProfessionsRouteImport } from './routes/_public/training.professions'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevelopmentRoute =
  AuthenticatedDevelopmentRouteImport.update({
    id: '/development',
    path: '/development',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGamificationRoute =
  AuthenticatedGamificationRouteImport.update({
    id: '/gamification',
    path: '/gamification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsRoute = AuthenticatedTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicConsentRoute = PublicConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactsRoute = PublicContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicManagementRoute = PublicManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDevelopmentRoute =
  AuthenticatedAdminDevelopmentRouteImport.update({
    id: '/development',
    path: '/development',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDictionariesRoute =
  AuthenticatedAdminDictionariesRouteImport.update({
    id: '/dictionaries',
    path: '/dictionaries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExportRoute =
  AuthenticatedAdminExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGamificationRoute =
  AuthenticatedAdminGamificationRouteImport.update({
    id: '/gamification',
    path: '/gamification',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMaterialsRoute =
  AuthenticatedAdminMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrgRoute = AuthenticatedAdminOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProductionRoute =
  AuthenticatedAdminProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTestsRoute = AuthenticatedAdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedLearningIndexRoute =
  AuthenticatedLearningIndexRouteImport.update({
    id: '/learning/',
    path: '/learning/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningCourseIdRoute =
  AuthenticatedLearningCourseIdRouteImport.update({
    id: '/learning/$courseId',
    path: '/learning/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionsIndexRoute =
  AuthenticatedProfessionsIndexRouteImport.update({
    id: '/professions/',
    path: '/professions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfessionsSlugRoute =
  AuthenticatedProfessionsSlugRouteImport.update({
    id: '/professions/$slug',
    path: '/professions/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestProfessionIdRoute =
  AuthenticatedTestProfessionIdRouteImport.update({
    id: '/test/$professionId',
    path: '/test/$professionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicTrainingIndexRoute = PublicTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTrainingProfessionsRoute =
  PublicTrainingProfessionsRouteImport.update({
    id: '/training/professions',
    path: '/training/professions',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/gamification': typeof AuthenticatedGamificationRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/about': typeof PublicAboutRoute
  '/consent': typeof PublicConsentRoute
  '/contacts': typeof PublicContactsRoute
  '/faq': typeof PublicFaqRoute
  '/management': typeof PublicManagementRoute
  '/privacy': typeof PublicPrivacyRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/development': typeof AuthenticatedAdminDevelopmentRoute
  '/admin/dictionaries': typeof AuthenticatedAdminDictionariesRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/gamification': typeof AuthenticatedAdminGamificationRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/org': typeof AuthenticatedAdminOrgRoute
  '/admin/production': typeof AuthenticatedAdminProductionRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/learning/$courseId': typeof AuthenticatedLearningCourseIdRoute
  '/professions/$slug': typeof AuthenticatedProfessionsSlugRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/test/$professionId': typeof AuthenticatedTestProfessionIdRoute
  '/training/professions': typeof PublicTrainingProfessionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/learning/': typeof AuthenticatedLearningIndexRoute
  '/professions/': typeof AuthenticatedProfessionsIndexRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
  '/training/': typeof PublicTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/gamification': typeof AuthenticatedGamificationRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tests': typeof AuthenticatedTestsRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/about': typeof PublicAboutRoute
  '/consent': typeof PublicConsentRoute
  '/contacts': typeof PublicContactsRoute
  '/faq': typeof PublicFaqRoute
  '/management': typeof PublicManagementRoute
  '/privacy': typeof PublicPrivacyRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/development': typeof AuthenticatedAdminDevelopmentRoute
  '/admin/dictionaries': typeof AuthenticatedAdminDictionariesRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/gamification': typeof AuthenticatedAdminGamificationRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/org': typeof AuthenticatedAdminOrgRoute
  '/admin/production': typeof AuthenticatedAdminProductionRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/learning/$courseId': typeof AuthenticatedLearningCourseIdRoute
  '/professions/$slug': typeof AuthenticatedProfessionsSlugRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/test/$professionId': typeof AuthenticatedTestProfessionIdRoute
  '/training/professions': typeof PublicTrainingProfessionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/learning': typeof AuthenticatedLearningIndexRoute
  '/professions': typeof AuthenticatedProfessionsIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/training': typeof PublicTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/development': typeof AuthenticatedDevelopmentRoute
  '/_authenticated/gamification': typeof AuthenticatedGamificationRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tests': typeof AuthenticatedTestsRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/consent': typeof PublicConsentRoute
  '/_public/contacts': typeof PublicContactsRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/management': typeof PublicManagementRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/development': typeof AuthenticatedAdminDevelopmentRoute
  '/_authenticated/admin/dictionaries': typeof AuthenticatedAdminDictionariesRoute
  '/_authenticated/admin/export': typeof AuthenticatedAdminExportRoute
  '/_authenticated/admin/gamification': typeof AuthenticatedAdminGamificationRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/_authenticated/admin/org': typeof AuthenticatedAdminOrgRoute
  '/_authenticated/admin/production': typeof AuthenticatedAdminProductionRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/learning/$courseId': typeof AuthenticatedLearningCourseIdRoute
  '/_authenticated/professions/$slug': typeof AuthenticatedProfessionsSlugRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/test/$professionId': typeof AuthenticatedTestProfessionIdRoute
  '/_public/training/professions': typeof PublicTrainingProfessionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/learning/': typeof AuthenticatedLearningIndexRoute
  '/_authenticated/professions/': typeof AuthenticatedProfessionsIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
  '/_public/training/': typeof PublicTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/certificates'
    | '/company'
    | '/dashboard'
    | '/development'
    | '/gamification'
    | '/library'
    | '/products'
    | '/profile'
    | '/tests'
    | '/videos'
    | '/about'
    | '/consent'
    | '/contacts'
    | '/faq'
    | '/management'
    | '/privacy'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/development'
    | '/admin/dictionaries'
    | '/admin/export'
    | '/admin/gamification'
    | '/admin/import'
    | '/admin/materials'
    | '/admin/org'
    | '/admin/production'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tests'
    | '/admin/users'
    | '/learning/$courseId'
    | '/professions/$slug'
    | '/results/$attemptId'
    | '/test/$professionId'
    | '/training/professions'
    | '/admin/'
    | '/learning/'
    | '/professions/'
    | '/results/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/certificates'
    | '/company'
    | '/dashboard'
    | '/development'
    | '/gamification'
    | '/library'
    | '/products'
    | '/profile'
    | '/tests'
    | '/videos'
    | '/about'
    | '/consent'
    | '/contacts'
    | '/faq'
    | '/management'
    | '/privacy'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/development'
    | '/admin/dictionaries'
    | '/admin/export'
    | '/admin/gamification'
    | '/admin/import'
    | '/admin/materials'
    | '/admin/org'
    | '/admin/production'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tests'
    | '/admin/users'
    | '/learning/$courseId'
    | '/professions/$slug'
    | '/results/$attemptId'
    | '/test/$professionId'
    | '/training/professions'
    | '/admin'
    | '/learning'
    | '/professions'
    | '/results'
    | '/training'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/certificates'
    | '/_authenticated/company'
    | '/_authenticated/dashboard'
    | '/_authenticated/development'
    | '/_authenticated/gamification'
    | '/_authenticated/library'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/tests'
    | '/_authenticated/videos'
    | '/_public/about'
    | '/_public/consent'
    | '/_public/contacts'
    | '/_public/faq'
    | '/_public/management'
    | '/_public/privacy'
    | '/_public/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/development'
    | '/_authenticated/admin/dictionaries'
    | '/_authenticated/admin/export'
    | '/_authenticated/admin/gamification'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/materials'
    | '/_authenticated/admin/org'
    | '/_authenticated/admin/production'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tests'
    | '/_authenticated/admin/users'
    | '/_authenticated/learning/$courseId'
    | '/_authenticated/professions/$slug'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/test/$professionId'
    | '/_public/training/professions'
    | '/_authenticated/admin/'
    | '/_authenticated/learning/'
    | '/_authenticated/professions/'
    | '/_authenticated/results/'
    | '/_public/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/development': {
      id: '/_authenticated/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof AuthenticatedDevelopmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gamification': {
      id: '/_authenticated/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof AuthenticatedGamificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests': {
      id: '/_authenticated/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AuthenticatedTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/consent': {
      id: '/_public/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof PublicConsentRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contacts': {
      id: '/_public/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof PublicContactsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/management': {
      id: '/_public/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof PublicManagementRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/development': {
      id: '/_authenticated/admin/development'
      path: '/development'
      fullPath: '/admin/development'
      preLoaderRoute: typeof AuthenticatedAdminDevelopmentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dictionaries': {
      id: '/_authenticated/admin/dictionaries'
      path: '/dictionaries'
      fullPath: '/admin/dictionaries'
      preLoaderRoute: typeof AuthenticatedAdminDictionariesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/export': {
      id: '/_authenticated/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AuthenticatedAdminExportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gamification': {
      id: '/_authenticated/admin/gamification'
      path: '/gamification'
      fullPath: '/admin/gamification'
      preLoaderRoute: typeof AuthenticatedAdminGamificationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/materials': {
      id: '/_authenticated/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/org': {
      id: '/_authenticated/admin/org'
      path: '/org'
      fullPath: '/admin/org'
      preLoaderRoute: typeof AuthenticatedAdminOrgRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/production': {
      id: '/_authenticated/admin/production'
      path: '/production'
      fullPath: '/admin/production'
      preLoaderRoute: typeof AuthenticatedAdminProductionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tests': {
      id: '/_authenticated/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AuthenticatedAdminTestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/learning/': {
      id: '/_authenticated/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof AuthenticatedLearningIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning/$courseId': {
      id: '/_authenticated/learning/$courseId'
      path: '/learning/$courseId'
      fullPath: '/learning/$courseId'
      preLoaderRoute: typeof AuthenticatedLearningCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professions/': {
      id: '/_authenticated/professions/'
      path: '/professions'
      fullPath: '/professions/'
      preLoaderRoute: typeof AuthenticatedProfessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professions/$slug': {
      id: '/_authenticated/professions/$slug'
      path: '/professions/$slug'
      fullPath: '/professions/$slug'
      preLoaderRoute: typeof AuthenticatedProfessionsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test/$professionId': {
      id: '/_authenticated/test/$professionId'
      path: '/test/$professionId'
      fullPath: '/test/$professionId'
      preLoaderRoute: typeof AuthenticatedTestProfessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/training/': {
      id: '/_public/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof PublicTrainingIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/training/professions': {
      id: '/_public/training/professions'
      path: '/training/professions'
      fullPath: '/training/professions'
      preLoaderRoute: typeof PublicTrainingProfessionsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDevelopmentRoute: typeof AuthenticatedAdminDevelopmentRoute
  AuthenticatedAdminDictionariesRoute: typeof AuthenticatedAdminDictionariesRoute
  AuthenticatedAdminExportRoute: typeof AuthenticatedAdminExportRoute
  AuthenticatedAdminGamificationRoute: typeof AuthenticatedAdminGamificationRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminMaterialsRoute: typeof AuthenticatedAdminMaterialsRoute
  AuthenticatedAdminOrgRoute: typeof AuthenticatedAdminOrgRoute
  AuthenticatedAdminProductionRoute: typeof AuthenticatedAdminProductionRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestsRoute: typeof AuthenticatedAdminTestsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
    AuthenticatedAdminDevelopmentRoute: AuthenticatedAdminDevelopmentRoute,
    AuthenticatedAdminDictionariesRoute: AuthenticatedAdminDictionariesRoute,
    AuthenticatedAdminExportRoute: AuthenticatedAdminExportRoute,
    AuthenticatedAdminGamificationRoute: AuthenticatedAdminGamificationRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminMaterialsRoute: AuthenticatedAdminMaterialsRoute,
    AuthenticatedAdminOrgRoute: AuthenticatedAdminOrgRoute,
    AuthenticatedAdminProductionRoute: AuthenticatedAdminProductionRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTestsRoute: AuthenticatedAdminTestsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevelopmentRoute: typeof AuthenticatedDevelopmentRoute
  AuthenticatedGamificationRoute: typeof AuthenticatedGamificationRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTestsRoute: typeof AuthenticatedTestsRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedLearningCourseIdRoute: typeof AuthenticatedLearningCourseIdRoute
  AuthenticatedProfessionsSlugRoute: typeof AuthenticatedProfessionsSlugRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedTestProfessionIdRoute: typeof AuthenticatedTestProfessionIdRoute
  AuthenticatedLearningIndexRoute: typeof AuthenticatedLearningIndexRoute
  AuthenticatedProfessionsIndexRoute: typeof AuthenticatedProfessionsIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevelopmentRoute: AuthenticatedDevelopmentRoute,
  AuthenticatedGamificationRoute: AuthenticatedGamificationRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTestsRoute: AuthenticatedTestsRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedLearningCourseIdRoute: AuthenticatedLearningCourseIdRoute,
  AuthenticatedProfessionsSlugRoute: AuthenticatedProfessionsSlugRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedTestProfessionIdRoute: AuthenticatedTestProfessionIdRoute,
  AuthenticatedLearningIndexRoute: AuthenticatedLearningIndexRoute,
  AuthenticatedProfessionsIndexRoute: AuthenticatedProfessionsIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicConsentRoute: typeof PublicConsentRoute
  PublicContactsRoute: typeof PublicContactsRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicManagementRoute: typeof PublicManagementRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicTrainingProfessionsRoute: typeof PublicTrainingProfessionsRoute
  PublicTrainingIndexRoute: typeof PublicTrainingIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicConsentRoute: PublicConsentRoute,
  PublicContactsRoute: PublicContactsRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicManagementRoute: PublicManagementRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicTrainingProfessionsRoute: PublicTrainingProfessionsRoute,
  PublicTrainingIndexRoute: PublicTrainingIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
